### ISSUE TITLE
Support for batch workloads

### ISSUE THREAD

**Issue by bhperry** [open-cluster-management-io/enhancements#138]
# Issue
Currently there is not good support for workloads which are expected to complete and be deleted from the spoke cluster where they were assigned. For example, simply creating a ManifestWork that wraps a Job with `ttlSecondsAfterFinished` set will always attempt to re-create the job after it is deleted by the spoke cluster's job controller. As far as I can tell, there is currently no way to express that a ManifestWork should be deleted when its subresources have completed.

~For CronJobs it would be useful to be able to make new placement decisions every time a Job is scheduled. Wrapping a CronJob in ManifestWork will of course only schedule jobs on a single spoke cluster, whereas wrapping it in a ManifestWorkReplicaSet will not have good guarantees of properly following the schedule when migrating between spoke clusters (e.g. if workload is migrated from cluster-A to cluster-B around the time the schedule would have triggered, it may miss that execution entirely and have to wait for the next scheduled time before running).~

# Possible Solutions
To address the issue of completable workloads like Jobs or non-restartable Pods, one possible solution would be to add additional fields to ManifestWork that instruct it to inspect one or more of its workloads for completion (under `spec.manifestConfigs`). Completed workloads would never be restarted, and when they have all reached their completed state the associated ManifestWork would be deleted. (e.g. a ManifestWork with a Job and a ConfigMap could be configured to wait until the Job completes, then be deleted along with the Job and ConfigMap). Just as a rough idea borrowing from the format of feedbackRules, it could look something like:
```
spec:
  manifestConfigs:
    - resourceIdentifier:
        group: batch
        resource: jobs
        namespace: ns
        name: myjob
      completionRules:
        - type: WellKnownCompletions
        - type: JSONPaths
          jsonPaths:
           - path: ".status.conditions[?(@.type=='Complete')].status"
             value: "True"
```
Could also consider adding a type `Deleted` which will consider a workload to be complete when it is deleted by another controller (e.g. the spoke cluster's job controller based on a very short `ttlSecondsAfterFinished`). Properly handling completion rules (especially a `Deleted` rule) would likely require registering a finalizer on the associated objects in order to have better guarantees of reconciliation.

~To handle the case of a CronJob-like object that is able to distribute work across multiple spoke clusters I think a new kind would make the most sense, named something like ManifestWorkCronJob. It would be very similar to ManifestWorkReplicaSet with additional fields from CronJob like `schedule`, `concurrencyPolicy`, etc. Presumably you would want to configure the `manifestWorkTemplate` to be completable (as described above) so the created ManifestWorks would get automatically cleaned up.~
